### ISSUE TITLE
Issue: Two Quickstarts are similarly named in JKube Website

### ISSUE THREAD

**Issue by Urjaswi-2655** [jkubeio/jkube-website#32]
Both Quickstarts are named the same [JKube Website](https://www.eclipse.org/jkube/quickstarts/) here i.e Maven:: Wildfly JAR but one is Wildfly JAR and the Other one is Wildfly JAR Slim.

![image](https://user-images.githubusercontent.com/65727814/160143003-f091ae30-d4f8-4b52-9db5-475f1a8ce873.png)

But As Per naming Convention one should be `Maven :: Wildfly JAR` and Other one should be `Maven :: Wildfly JAR :: Slim`
Naming Convention is predicted with respect to` Maven :: Webapp :: Wildfly` and `Maven :: Webapp :: Wildfly :: Datasource`

![image](https://user-images.githubusercontent.com/65727814/160143162-6caddb38-b6df-47cf-aa4e-61832789bdf8.png)

This issue is referenced from [#1400](https://github.com/eclipse/jkube/issues/1400) in JKube Repo.

**Comment by manusa** [comment]
The names in the website come from the quickstart pom.xml files of the main repo.

**Comment by Urjaswi-2655** [comment]
Ok. Will try to work on it. But I figured out how to work on issue [#1394 ](https://github.com/eclipse/jkube/issues/1394). Will work on it at first.

**Comment by Urjaswi-2655** [comment]
> The names in the website come from the quickstart pom.xml files of the main repo.

@manusa I think, I just have to change https://github.com/eclipse/jkube/blob/119ec28c665a85c28ec4f4626206d5b91955bb12/quickstarts/maven/wildfly-jar-slim/pom.xml#L24  
This line Right?

**Comment by manusa** [comment]
yes

**Comment by Urjaswi-2655** [comment]
Resolved this issue [here](https://github.com/eclipse/jkube/pull/1401)
